name: Enviar correo electrónico

on:
  push:
    branches:
      - master

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Enviar correo electrónico
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com.
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Correo de prueba"
        body: "Este es un correo electrónico de prueba enviado desde GitHub Actions."
        from: oteronicolas3@gmail.com
        to: oteronicolas3@gmail.com